Algoritmo "semnome"

Var

user, password: caractere

Inicio

escreva ("Digite o seu usuário: ")
leia(user)
escreva("Didite a sua senha: ")
Leia(password)

enquanto (user <> "admin") ou (password <> "admin") faca
     escreval("Usuário ou Senha inválidos")
     escreva ("Digite o seu usuário: ")
     leia(user)
     escreva("Didite a sua senha: ")
     leia(password)
fimenquanto

escreval ("Seja bem vindo ao sistema")


Fimalgoritmo